config/routes.rb
PaintingGallery::Application.routes.draw do
  resources :paintings

  root :to => "paintings#index"

end

app/models/painting.rb
class Painting < ActiveRecord::Base
  validates :title, :presence => true, :uniqueness => true
  validates :image, :presence => true
  has_attached_file :image,
    :styles => { :thumb => "100x100#" },
    :storage => :s3,
    :bucket => 'painting_gallery',
    :s3_credentials => S3_CREDENTIALS
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def index
    @paintings = Painting.all
  end

  def new
    @painting = Painting.new
  end

  def create
    @painting = Painting.new(params[:painting])

    if @painting.save
      redirect_to :action => :index, :notice => "#{ @painting.title } was successfully created."
    else
      render :action => "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Painting Gallery
    = stylesheet_link_tag 'screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'print.css', :media => 'print'
    /[if lt IE 8]
      = stylesheet_link_tag 'ie.css', :media => 'screen, projection'
    = stylesheet_link_tag 'jquery.fancybox-1.3.4', :media => 'screen, projection'
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js'
    = javascript_include_tag :all
    = csrf_meta_tag
  %body.two-col
    #container
      #header
        %h1 Painting Gallery
        %h2 Rails file upload experiment
      #sidebar
        %ul.menu
          %li= link_to 'View all paintings', paintings_path
          %li= link_to 'Add new painting', new_painting_path
      #content
        - if alert
          #alert= alert
        - if notice
          #notice= notice
        = yield
      #footer
        %p Made by #{ link_to "Jeff Dickey", "http://jeffdickey.info/" }

app/views/paintings/index.html.haml
.paintings
  %h2 Viewing all paintings
  - @paintings.each do |painting|
    %a.fancybox{ :href => painting.image.url, :title => painting.title, :rel => 'gallery' }
      = image_tag painting.image.url(:thumb), :alt => painting.title
      %span= truncate(painting.title, :length => 15)

app/views/paintings/new.html.haml
.new
  %h2 Add new painting
  = form_for(@painting, :html => {:multipart => true}) do |f|
    - if @painting.errors.any?
      #error_explanation
        %h3
          = pluralize(@painting.errors.count, "error")
          prohibited this painting from being saved:
        %ul
          - @painting.errors.full_messages.each do |msg|
            %li= msg
    .field
      = f.label :title
      %br/
      = f.text_field :title
    .field.file
      = f.file_field :image
    .actions
      = f.submit 'Add new painting'